name: Add To Merge Queue
on:
  pull_request:
    types: [labeled, opened, reopened]

jobs:
  add-to-merge-queue:
    name:
      Add to Merge Queue if the PR is labelled with any of the automerge labels
    runs-on: ubuntu-latest

    steps:
      - name: Log github event
        env:
          $GITHUB_CONTEXT_LABELS:
            ${{ toJson(github.event.pull_request.labels) }}
        run: echo "$GITHUB_CONTEXT_LABELS"
      - name: 'Add the PR to the merge queue via the GitHub CLI'
        if:
          ${{ contains(github.event.pull_request.labels.*.name,
          format('status{0} ready to merge 🎉', ':')) ||
          contains(github.event.pull_request.labels.*.name, format('status{0}
          enable automerge 🟠', ':'))}}
        run: gh pr merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
