name: Contribution triage - proposal accepted and community contribution
on:
  issues:
    types: [labeled, opened]

permissions:
  issues: write

jobs:
  add-comment:
    name: Add comment to issues with proposal accepted and community contribution
    runs-on: ubuntu-latest
    steps:
      - name: Log github event
        env:
          $GITHUB_CONTEXT_LABELS: ${{ toJson(github.event.label) }}
        run: echo "$GITHUB_CONTEXT_LABELS"
      - name: Conditional Check and Add Comment
        id: conditional-comment
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 #v6.4.1
        with:
          script: |
            response = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const labelArray = response.data.map((label) => label.name)

            console.log('label array here', labelArray)

            if ((labelArray.includes('proposal: accepted') && labelArray.includes('community contribution')) || (labelArray.includes('community contribution') && labelArray.includes('proposal: accepted'))) {
              console.log('we are adding a comment to the issue...');
            } else {
              console.log('No comment added because the conditions are not met.');
            }
      - name: Set Output
        if: steps.conditional-comment.outcome == 'success'
        run: echo "Comment added successfully."
