name: Contribution triage - proposal accepted and community contribution
on:
  issues:
    types: [labeled, opened]

permissions:
  issues: write

jobs:
  add-comment:
    name: Add comment to issues with proposal accepted and community contribution
    runs-on: ubuntu-latest
    steps:
      - name: Log github event
        env:
          $GITHUB_CONTEXT_LABELS: ${{ toJson(github.event.label) }}
        run: echo "$GITHUB_CONTEXT_LABELS"
      - name: Conditional Check and Add Comment
        id: conditional-comment
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 #v6.4.1
        with:
          script: |
            response = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            events = await github.rest.issues.listEvents({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const eventsArray = events.data.map((label) => label)


            const labelArray = response.data.map((label) => label.name)

            const commentsArray = comments.data.map(comment => comment.body)

            const commentText = "The Carbon team has accepted this proposal! Our team doesn't have the capacity to work on this now, so we are requesting community contributors. Please see the labels for roles that are needed. If you are willing to help out, comment below and we will get in touch!"

            const secondToLastEventTimestamp = new Date(eventsArray[eventsArray.length - 2].created_at)
            
            const lastEventTimestamp = new Date(eventsArray[eventsArray.length - 1].created_at)

            const differenceInSeconds = Math.abs((lastEventTimestamp - secondToLastEventTimestamp)/1000)

            console.log('seconds', differenceInSeconds)
            
            if (labelArray.includes('proposal: accepted') && labelArray.includes('needs: community contribution') && !commentsArray.includes(commentText)) {
              setTimeOut(() => {
                if(!commentsArray.includes(commentText)) {
                  github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: commentText
                  });
                }
              }, 2000)
            } else {
              console.log('No comment added because the conditions are not met.');
            }
      - name: Set Output
        if: steps.conditional-comment.outcome == 'success'
        run: echo "Comment added successfully."
